name: process-prode-results
on:
  # schedule:
  #   - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: update-points-after-race-results
        run: |
          curl --request POST \
          --url 'https://prodef1.vercel.app/api/processProdeResults' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
