name: hourly-cron-job
on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: update-after-race-results
        run: |
          curl --request POST \
          --url 'https://prodef1.vercel.app/api/cronJob' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
